/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#2563eb',
        'on-background': '#131b2e',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-container-lowest': '#ffffff',
        'outline': '#737686',
        'tertiary-container': '#6b6e70',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#434655',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#e0e3e5',
        'surface-tint': '#0053db',
        'surface-container-highest': '#dae2fd',
        'error': '#ba1a1a',
        'surface': '#faf8ff',
        'surface-bright': '#faf8ff',
        'tertiary': '#525657',
        'surface-container': '#eaedff',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#eff1f3',
        'on-primary-fixed-variant': '#003ea8',
        'secondary': '#515f74',
        'on-secondary-fixed': '#0d1c2e',
        'secondary-container': '#d5e3fc',
        'on-surface': '#131b2e',
        'inverse-primary': '#b4c5ff',
        'primary-fixed': '#dbe1ff',
        'surface-container-low': '#f2f3ff',
        'inverse-surface': '#283044',
        'on-primary-fixed': '#00174b',
        'on-secondary-container': '#57657a',
        'surface-variant': '#dae2fd',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'background': '#faf8ff',
        'inverse-on-surface': '#eef0ff',
        'on-secondary-fixed-variant': '#3a485b',
        'secondary-fixed-dim': '#b9c7df',
        'outline-variant': '#c3c6d7',
        'secondary-fixed': '#d5e3fc',
        'surface-container-high': '#e2e7ff',
        'on-primary-container': '#eeefff',
        'on-tertiary-fixed-variant': '#444749',
        'on-error-container': '#93000a',
        'primary': '#004ac6',
      },
      spacing: {
        'gutter': '20px',
        'container-max': '1280px',
        'unit': '6px',
        'stack-sm': '10px',
        'stack-md': '20px',
        'margin-mobile': '16px',
        'stack-lg': '40px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'mono': ['Geist Mono', 'monospace'],
        'body-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'display': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['21px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['27px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'mono': ['12px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['15px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg-mobile': ['21px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0',
        lg: '0',
        xl: '0',
        full: '0',
      },
    },
  },
  plugins: [],
}
